"""add composite index on metrics computer_id collected_at

Revision ID: 2c5998637761
Revises: 9d35e8085691
Create Date: 2026-07-23 21:23:23.834171

"""

from collections.abc import Sequence

from alembic import op

revision: str = "2c5998637761"
down_revision: str | None = "9d35e8085691"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metrics_computer_id"), table_name="metrics")
    op.create_index(
        "ix_metrics_computer_id_collected_at",
        "metrics",
        ["computer_id", "collected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_metrics_computer_id_collected_at", table_name="metrics")
    op.create_index(op.f("ix_metrics_computer_id"), "metrics", ["computer_id"], unique=False)
    # ### end Alembic commands ###
